In [ ]:
#here i took three inputs and three weights corresponding to those inputs and a bias term and found out the output of the neuron
#three inputs and one neuron
inputs = [1,2,3] # list 
weights = [0.2,0.8,-0.5] # list 
bias = 2 
#multiplied elements of the list 
out = (inputs[0] * weights[0] + inputs[1] * weights[1] + inputs[2]* weights[2] + bias)
print(out)

2.3


In [2]:
inputs = [1,2,3,2.5]
#here we have 4 inputs and we are training 3 neurons wir
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]

weights1 = weights[0]
weights2 = weights[1]
weights3 = weights[2]
bias1 = 2 
bias2 = 3 
bias3 = 0.5
outputs = [
    #neuron1 
inputs[0]*weights1[0] +
inputs[1]*weights1[1] +
inputs[2]*weights1[2] +
inputs[3]*weights1[3] + bias1,

inputs[0]*weights2[0] +
inputs[1]*weights2[1] +
inputs[2]*weights2[2] +
inputs[3]*weights2[3] + bias2,

inputs[0]*weights3[0] +
inputs[1]*weights3[1] +
inputs[2]*weights3[2] +
inputs[3]*weights3[3] + bias3,
]
print(outputs)

[4.8, 1.21, 2.385]


In [4]:
inputs = [1,2,3,2.5]

#list of weights 
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]

#list of biasis 
biases = [2,3,0.5]

layer_output = []

#for each neuron 
for neuron_weights , neuron_bias in zip(weights,biases):
    neuron_output = 0
    for n_input , weight in zip(inputs , neuron_weights):
        neuron_output += n_input*weight
    neuron_output += neuron_bias
    layer_output.append(neuron_output)
print(layer_output)


[4.8, 1.21, 2.385]


now we will see how numpy is useful in matrix and vector multiplication in case of a neuron training 

In [ ]:
import numpy as np 
inputs = [1.0,2.0,3.0,2.5]
weights = [0.2,0.8,-0.5,1.0]
bias = 2.0
#we can write either the dot product of vectors because the dot products answer remains the same in case of vectors
outputs = np.dot(weights,inputs) + bias 
outputs = np.dot(inputs,weights) + bias 
print(outputs)

4.8


so here we have one vector that is inputs and other matrix that  is weights and we are doing vector matrix multiplication here so that the output we get is in the correct sequence of matrix 

In [1]:
import numpy as np 
inputs = [1.0,2.0,3.0,2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0,3.0,0.5]

#convert list into numpy array 
input_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)

layer_output = np.dot(weights_array,input_array) + biases_array
print(layer_output)

[4.8   1.21  2.385]


#here now we are going to multiply two mtrices together and we have to check for the dimension of both matrices so that we can multiply them if that is not happening them we have to take transose of one matrix so that it can be multiplied with other matrix or we have to apply similar operations to them so to make matrix multiplication reasonable

In [7]:
import numpy as np 
inputs = [[1.0, 2.0, 3.0, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1],[0.5, -0.91, 0.26, -0.5],[-0.26, -0.27, 0.17, 0.87]]
biases = [2.0,3.0,0.5]
#convert list to array as with array only we can use transpose 
inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)
outputs = np.dot(inputs_array , weights_array.T) + biases_array
print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


now we are going for multiple layers in a neural network in which we are given the inputs to a neuron and subsiquent weight corresponding to the weight matrix 

In [ ]:
import numpy as np 
inputs = [[1, 2, 3, 2.5],
          [2., 5., -1., 2],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
           
biases = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]
#convert lists to numpy 
inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)
weights2_array = np.array(weights2)
biases2_array = np.array(biases2)

#calculate the output to the first layer 
layer1_outputs = np.dot(inputs_array,weights_array.T)+biases_array
#calculate the output of the second layer 
layer2_outputs = np.dot(layer1_outputs,weights2_array.T)+biases2_array
print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]
